### ISSUE TITLE
pip install failing on M1 OSX Big Sur 11.6

### ISSUE THREAD

**Issue by bitkarrot** [rustyrussell/secp256k1-py#7]
I'm on python 3.8.13 on M1 OSX BigSur, 

when i run

```pip install --no-binary :all: secp256k1```

the following error occurs

```
pip install secp256k1
Collecting secp256k1
  Using cached secp256k1-0.14.0.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      0.29.2
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error

        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [10 lines of output]
            WARNING: The wheel package is not available.
            WARNING: The wheel package is not available.
            WARNING: The wheel package is not available.
            WARNING: The wheel package is not available.
            usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
               or: setup.py --help [cmd1 cmd2 ...]
               or: setup.py --help-commands
               or: setup.py cmd --help

            error: invalid command 'bdist_wheel'
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pytest-runner
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "/Users/bitcarrot/lngifts/lnbits-legend/env/lib/python3.8/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/Users/bitcarrot/.pyenv/versions/3.8.13/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/bitcarrot/lngifts/lnbits-legend/env/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/y5/5_y1mtqd4jl_x3yk_5pnm4jr0000gn/T/tmpeiqe9a44', '--quiet', 'pytest-runner==2.6.2']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/y5/5_y1mtqd4jl_x3yk_5pnm4jr0000gn/T/pip-install-b2sdfb1b/secp256k1_e343ec56f32d450ca60c1c4f91c5c705/setup.py", line 265, in <module>
          setup(
        File "/Users/bitcarrot/lngifts/lnbits-legend/env/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/Users/bitcarrot/lngifts/lnbits-legend/env/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/bitcarrot/lngifts/lnbits-legend/env/lib/python3.8/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/bitcarrot/lngifts/lnbits-legend/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/bitcarrot/lngifts/lnbits-legend/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "/Users/bitcarrot/lngifts/lnbits-legend/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
          return installer(requirement)
        File "/Users/bitcarrot/lngifts/lnbits-legend/env/lib/python3.8/site-packages/setuptools/dist.py", line 780, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/bitcarrot/lngifts/lnbits-legend/env/lib/python3.8/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/Users/bitcarrot/lngifts/lnbits-legend/env/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/y5/5_y1mtqd4jl_x3yk_5pnm4jr0000gn/T/tmpeiqe9a44', '--quiet', 'pytest-runner==2.6.2']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by callebtc** [comment]
This should help:
```bash
pip install wheel
```

**Comment by bitkarrot** [comment]
> This should help:
> 
> ```shell
> pip install wheel
> ```

yup that fixed it for now
